name: Build and deploy Next.js app to Azure Web App - app-step4-30

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app (disable lint)
        run: npm run build --no-lint

      - name: Verify .next folder exists # 新しいステップを追加
        run: |
          ls -l .next/ # .next フォルダの中身を確認
          if [ ! -d ".next" ]; then
            echo ".next directory was not created. Build might have failed or output to wrong location."
            exit 1 # エラーとしてジョブを終了
          fi

      - name: Upload .next folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build-output
          path: ./.next

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build-output
          path: ./app-root

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-step4-30'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D29A8EE5EAA1438AAB1031E108B66CA7 }}
          package: ./app-root/.next