name: Deploy Next.js to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install --force

    - name: Build Next.js app
      run: npm run build # package.jsonのbuildスクリプトを呼び出すだけ
      env: # ★このenvブロックを追加★
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }} # secretsから値を渡す

    - name: Upload production-ready assets
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-standalone-output
        path: ./.next/standalone

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: nextjs-standalone-output

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'app-step4-30'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        # startup-command: 'node server.js' # App Serviceの構成で設定済みのため、この行は削除またはコメントアウトを推奨