name: Deploy Next.js to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions:setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install --force

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Debug NEXT_PUBLIC_API_URL before build # ★このステップを追加★
      run: |
        echo "Value from secret: ${{ secrets.NEXT_PUBLIC_API_URL }}"
        echo "Length of secret value: ${{ secrets.NEXT_PUBLIC_API_URL | length }}"
        # 環境変数として設定された値も確認 (これはnpm run buildで渡す形式なのでここでは未設定かも)
        echo "NEXT_PUBLIC_API_URL env var (if set): $NEXT_PUBLIC_API_URL"
      env: # このenvブロックは、次のrunで参照される変数を設定
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }} # シークレットの値をこのステップの環境変数に設定

    - name: Build Next.js app
      run: NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} npm run build

    - name: Upload production-ready assets
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-standalone-output
        path: ./.next/standalone

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: nextjs-standalone-output

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'app-step4-30'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
